name: mapsindoors_mapbox_ios
description: iOS implementation of the mapsindoors plugin  using the Mapbox platform
version: 3.1.0
repository: https://github.com/MapsPeople/mapsindoors_flutter_mapbox_ios
homepage: https://www.mapsindoors.com/

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: mapsindoors
    platforms:
      ios:
        pluginClass: MapsIndoorsPlugin

dependencies:
  flutter:
    sdk: flutter
  mapsindoors_platform_interface: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0